/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AuthLoggedOutRouteImport } from './routes/_auth/logged-out'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthSessionChangedRouteImport } from './routes/_auth/session-changed'
import { Route as AuthSessionEndedRouteImport } from './routes/_auth/session-ended'
import { Route as AuthSsoErrorRouteImport } from './routes/_auth/sso-error'
import { Route as AppAccountConnectionsRouteImport } from './routes/_app/account/connections'
import { Route as AuthLinkTxIdRouteImport } from './routes/_auth/link/$txId'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthLoggedOutRoute = AuthLoggedOutRouteImport.update({
  id: '/logged-out',
  path: '/logged-out',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSessionChangedRoute = AuthSessionChangedRouteImport.update({
  id: '/session-changed',
  path: '/session-changed',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSessionEndedRoute = AuthSessionEndedRouteImport.update({
  id: '/session-ended',
  path: '/session-ended',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSsoErrorRoute = AuthSsoErrorRouteImport.update({
  id: '/sso-error',
  path: '/sso-error',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AppAccountConnectionsRoute = AppAccountConnectionsRouteImport.update({
  id: '/account/connections',
  path: '/account/connections',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthLinkTxIdRoute = AuthLinkTxIdRouteImport.update({
  id: '/link/$txId',
  path: '/link/$txId',
  getParentRoute: () => AuthRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/logged-out': typeof AuthLoggedOutRoute
  '/login': typeof AuthLoginRoute
  '/session-changed': typeof AuthSessionChangedRoute
  '/session-ended': typeof AuthSessionEndedRoute
  '/sso-error': typeof AuthSsoErrorRoute
  '/account/connections': typeof AppAccountConnectionsRoute
  '/link/$txId': typeof AuthLinkTxIdRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/logged-out': typeof AuthLoggedOutRoute
  '/login': typeof AuthLoginRoute
  '/session-changed': typeof AuthSessionChangedRoute
  '/session-ended': typeof AuthSessionEndedRoute
  '/sso-error': typeof AuthSsoErrorRoute
  '/account/connections': typeof AppAccountConnectionsRoute
  '/link/$txId': typeof AuthLinkTxIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_auth/logged-out': typeof AuthLoggedOutRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/session-changed': typeof AuthSessionChangedRoute
  '/_auth/session-ended': typeof AuthSessionEndedRoute
  '/_auth/sso-error': typeof AuthSsoErrorRoute
  '/_app/': typeof AppIndexRoute
  '/_app/account/connections': typeof AppAccountConnectionsRoute
  '/_auth/link/$txId': typeof AuthLinkTxIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/logged-out'
    | '/login'
    | '/session-changed'
    | '/session-ended'
    | '/sso-error'
    | '/account/connections'
    | '/link/$txId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/logged-out'
    | '/login'
    | '/session-changed'
    | '/session-ended'
    | '/sso-error'
    | '/account/connections'
    | '/link/$txId'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_auth/logged-out'
    | '/_auth/login'
    | '/_auth/session-changed'
    | '/_auth/session-ended'
    | '/_auth/sso-error'
    | '/_app/'
    | '/_app/account/connections'
    | '/_auth/link/$txId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_auth/logged-out': {
      id: '/_auth/logged-out'
      path: '/logged-out'
      fullPath: '/logged-out'
      preLoaderRoute: typeof AuthLoggedOutRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/session-changed': {
      id: '/_auth/session-changed'
      path: '/session-changed'
      fullPath: '/session-changed'
      preLoaderRoute: typeof AuthSessionChangedRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/session-ended': {
      id: '/_auth/session-ended'
      path: '/session-ended'
      fullPath: '/session-ended'
      preLoaderRoute: typeof AuthSessionEndedRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/sso-error': {
      id: '/_auth/sso-error'
      path: '/sso-error'
      fullPath: '/sso-error'
      preLoaderRoute: typeof AuthSsoErrorRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_app/account/connections': {
      id: '/_app/account/connections'
      path: '/account/connections'
      fullPath: '/account/connections'
      preLoaderRoute: typeof AppAccountConnectionsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_auth/link/$txId': {
      id: '/_auth/link/$txId'
      path: '/link/$txId'
      fullPath: '/link/$txId'
      preLoaderRoute: typeof AuthLinkTxIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppAccountConnectionsRoute: typeof AppAccountConnectionsRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppAccountConnectionsRoute: AppAccountConnectionsRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthLoggedOutRoute: typeof AuthLoggedOutRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSessionChangedRoute: typeof AuthSessionChangedRoute
  AuthSessionEndedRoute: typeof AuthSessionEndedRoute
  AuthSsoErrorRoute: typeof AuthSsoErrorRoute
  AuthLinkTxIdRoute: typeof AuthLinkTxIdRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoggedOutRoute: AuthLoggedOutRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSessionChangedRoute: AuthSessionChangedRoute,
  AuthSessionEndedRoute: AuthSessionEndedRoute,
  AuthSsoErrorRoute: AuthSsoErrorRoute,
  AuthLinkTxIdRoute: AuthLinkTxIdRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
